# Generated by Django 4.1.3 on 2022-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abv', models.FloatField()),
                ('price', models.IntegerField()),
                ('standard', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
